package main

var UserSchema = `
CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name TEXT NOT NULL,
	email TEXT NOT NULL UNIQUE,
	hashed_password TEXT NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);`

var ProfileSchema = `
CREATE TABLE IF NOT EXISTS profile (
	user_id INTEGER PRIMARY KEY references users(id),
	avatar TEXT NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
`

var PostsSchema = `CREATE TABLE IF NOT EXISTS posts (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	url TEXT NOT NULL,
	title TEXT NOT NULL UNIQUE,
    user_id INTEGER REFERENCES users(user_id) ON DELETE CASCADE,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);`

var CommentsSchema = `CREATE TABLE IF NOT EXISTS comments (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	body TEXT NOT NULL,
    post_id INTEGER REFERENCES posts(posts_id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users(users_id) ON DELETE CASCADE,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);`

var VotesSchema = `CREATE TABLE IF NOT EXISTS votes (
    post_id INTEGER REFERENCES posts(posts_id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users(users_id) ON DELETE CASCADE,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, post_id)
);`
